# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TVI Resources
email: ryhunsaker@dsdsmail.net
description: >-
  Practical resources for teachers of students with visual impairments
github_username: TVIResources
minimal_mistakes_skin: "aqua"
search: true
repository: TVIResources/TVIResources.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - templates/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Michael Ryan Hunsaker, M.Ed., Ph.D."
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Behavioral Neuroscientist who became a Teacher for Studrnts with Visual Impairments who loves to teach and write about assistive technology, visual impairments, and accessibility."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://tviresources.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mrhunsaker"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  enabled: true
  provider: staticman_v2
  staticman:
    branch                : "main"
    endpoint              : "https://staticman3.herokuapp.com/v3/entry/TVIResources/TVIResources.github.io/main"
    commit_message        : "New comment from {{ fields.name }}"
    filename              : comment-{@timestamp}
    format                : "yml"
    moderation: true
    allowedFields         : ["name", "email", "message"]
    requiredFields        : ["name", "email", "message"]
    path                  : "_data/comments"
    transforms            :
      email               : "md5"
    generatedFields:
      date: 
        type: "date"
        options:
          format: "iso8601"
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
